import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/shared/Navbar";

const yekanBakh = localFont({
  src: [
    {
      path: "./font/YekanBakh-ExtraBlack.ttf",
      weight: "900",
    },
    {
      path: "./font/YekanBakh-Black.ttf",
      weight: "800",
    },
    {
      path: "./font/YekanBakh-ExtraBold.ttf",
      weight: "700",
    },
    {
      path: "./font/YekanBakh-Bold.ttf",
      weight: "600",
    },
    {
      path: "./font/YekanBakh-SemiBold.ttf",
      weight: "500",
    },
    {
      path: "./font/YekanBakh-Regular.ttf",
      weight: "400",
    },
    {
      path: "./font/YekanBakh-Light.ttf",
      weight: "300",
    },
    {
      path: "./font/YekanBakh-Thin.ttf",
      weight: "200",
    },
  ],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${yekanBakh.className} antialiased`}>
        <Navbar />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
