import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Navbar from '@/components/shared/Navbar';
import Footer from '@/components/shared/Footer';

const yekanBakh = localFont({
  src: [
    {
      path: './font/YekanBakh-ExtraBlack.ttf',
      weight: '900',
    },
    {
      path: './font/YekanBakh-Black.ttf',
      weight: '800',
    },
    {
      path: './font/YekanBakh-ExtraBold.ttf',
      weight: '700',
    },
    {
      path: './font/YekanBakh-Bold.ttf',
      weight: '600',
    },
    {
      path: './font/YekanBakh-SemiBold.ttf',
      weight: '500',
    },
    {
      path: './font/YekanBakh-Regular.ttf',
      weight: '400',
    },
    {
      path: './font/YekanBakh-Light.ttf',
      weight: '300',
    },
    {
      path: './font/YekanBakh-Thin.ttf',
      weight: '200',
    },
  ],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body className={`${yekanBakh.className} antialiased`}>
        <Navbar />
        <main className="container">
          {modal}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
