import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Navbar from '@/components/shared/navbar/Navbar';
import Footer from '@/components/shared/Footer';
import { Toaster } from '@/components/ui/sonner';
import { ClerkProvider } from '@clerk/nextjs';
import NextTopLoader from 'nextjs-toploader';
import { auth, currentUser } from '@clerk/nextjs/server';
import { NextIntlClientProvider } from 'next-intl';
import { ThemeProvider } from '@/components/shared/ThemeProvider';

const yekanBakh = localFont({
  src: [
    {
      path: './font/YekanBakh-ExtraBlack.ttf',
      weight: '900',
    },
    {
      path: './font/YekanBakh-Black.ttf',
      weight: '800',
    },
    {
      path: './font/YekanBakh-ExtraBold.ttf',
      weight: '700',
    },
    {
      path: './font/YekanBakh-Bold.ttf',
      weight: '600',
    },
    {
      path: './font/YekanBakh-SemiBold.ttf',
      weight: '500',
    },
    {
      path: './font/YekanBakh-Regular.ttf',
      weight: '400',
    },
    {
      path: './font/YekanBakh-Light.ttf',
      weight: '300',
    },
    {
      path: './font/YekanBakh-Thin.ttf',
      weight: '200',
    },
  ],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale?: string }>;
}>) {
  const { userId } = await auth();
  const user = await currentUser();
  const locale = (await params).locale;
  return (
    <ClerkProvider>
      <html
        lang={locale}
        dir={locale == 'fa' ? 'rtl' : 'ltr'}
        suppressHydrationWarning
      >
        <body className={`${yekanBakh.className} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider>
              <Toaster position="top-right" />
              <NextTopLoader color="var(--primary)" showSpinner={false} />
              <Navbar
                isAuthenticated={!!userId}
                userEmail={user?.emailAddresses?.[0]?.emailAddress}
              />
              <main className="container">{children}</main>
              <Footer />
            </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
