import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
// import Navbar from '@/components/shared/Navbar/Navbar';
import Footer from '@/components/shared/Footer';
import AllProviders from '@/providers/AllProviders';
import { Suspense } from 'react';
import { auth } from '@clerk/nextjs/server';
import Navbar from '@/components/shared/Navbar/Navbar';
// import { auth } from '@clerk/nextjs/server';

const yekanBakh = localFont({
  src: [
    {
      path: './font/YekanBakh-ExtraBlack.ttf',
      weight: '900',
    },
    {
      path: './font/YekanBakh-Black.ttf',
      weight: '800',
    },
    {
      path: './font/YekanBakh-ExtraBold.ttf',
      weight: '700',
    },
    {
      path: './font/YekanBakh-Bold.ttf',
      weight: '600',
    },
    {
      path: './font/YekanBakh-SemiBold.ttf',
      weight: '500',
    },
    {
      path: './font/YekanBakh-Regular.ttf',
      weight: '400',
    },
    {
      path: './font/YekanBakh-Light.ttf',
      weight: '300',
    },
    {
      path: './font/YekanBakh-Thin.ttf',
      weight: '200',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'fa' }, { locale: 'ar' }];
}

async function NavSuspense(){
  const { isAuthenticated} = await auth();

  return (
    <Navbar isAuthenticated={isAuthenticated}/>
  )
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale?: string }>;
}>) {

  const locale = (await params).locale;
  return (
    <Suspense>
    <html
      lang={locale}
      dir={locale === 'en' ? 'ltr' : 'rtl'}
      suppressHydrationWarning
      className="selection:bg-primary/10"
    >
      <body className={`${yekanBakh.className} antialiased`}>
        <AllProviders>
            <Suspense>
              <NavSuspense/>
            </Suspense>
        
          <main className="container">{children}</main>
          <Footer />
        </AllProviders>
      </body>
    </html>
      </Suspense>
  );
}
