import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Navbar from '@/components/shared/Navbar/Navbar';
import Footer from '@/components/shared/Footer';
import { auth } from '@clerk/nextjs/server';
import AllProviders from '@/providers/AllProviders';

const yekanBakh = localFont({
  src: [
    {
      path: './font/YekanBakh-ExtraBlack.ttf',
      weight: '900',
    },
    {
      path: './font/YekanBakh-Black.ttf',
      weight: '800',
    },
    {
      path: './font/YekanBakh-ExtraBold.ttf',
      weight: '700',
    },
    {
      path: './font/YekanBakh-Bold.ttf',
      weight: '600',
    },
    {
      path: './font/YekanBakh-SemiBold.ttf',
      weight: '500',
    },
    {
      path: './font/YekanBakh-Regular.ttf',
      weight: '400',
    },
    {
      path: './font/YekanBakh-Light.ttf',
      weight: '300',
    },
    {
      path: './font/YekanBakh-Thin.ttf',
      weight: '200',
    },
  ],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale?: string }>;
}>) {
  const { userId } = await auth();

  const locale = (await params).locale;
  return (
    <html
      lang={locale}
      dir={locale === 'en' ? 'ltr' : 'rtl'}
      suppressHydrationWarning
      className="selection:bg-primary/10"
    >
      <body className={`${yekanBakh.className} antialiased`}>
        <AllProviders>
          <Navbar isAuthenticated={!!userId} />
          <main className="container">{children}</main>
          <Footer />
        </AllProviders>
      </body>
    </html>
  );
}
